name: EN Deployment

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        required: false
      source_branch:
        required: false
      commit_hash:
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: EN

      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci

      - run: npm start
