name: FR Deployment

on:
  workflow_dispatch:
    inputs:
      triggered_by:
        required: false
      source_branch:
        required: false
        default: 'FR'

env:
  REPO_B: 'roohmeiy/multi-branch-management'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_B }}
          ref: ${{ github.event.inputs.source_branch }}
          token: ${{ secrets.TOKEN }}
          
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - run: npm ci
      - run: npm start
