name: FR Deployment

on:
  repository_dispatch:
    types: [deploy-FR]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout FR branch
        uses: actions/checkout@v4
        with:
          ref: FR  

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm ci
      - run: npm start
