name: Deploy FR Application

on:
  repository_dispatch:
    types: [deploy-fr]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18  # You can adjust this version as needed

      - name: Install dependencies
        run: npm install

      - name: Run application
        run: npm run start
